#Set to false to prevent Chromatic Arsenal from injecting its own items into loot tables. This will cause items only found as loot (such as the Golden Heart) to become unobtainable, and it will be up to the modpack to add a method to obtain them. This setting also affects the Wandering Trader trade for Chroma Shards.
lootTableInsertion = true
#Whether super curios are allowed in slots other than super curio slots. Prevents equipping super curios in general purpose curio slots.
superCuriosOnlyInRespectiveSlot = true

[CurioSettings]

	[CurioSettings.GoldenHeartSettings]
		#The max health granted when the player equips a golden heart.
		#Range: 4.9E-324 ~ 1.7976931348623157E308
		maxHealthBoost = 4.0
		#The operation used for the health bonus. 0 for additive, 1 for multiply base, 2 for multiply total.
		#Range: 0 ~ 2
		maxHealthBoostOperation = 0
		#The level of the absorption effect applied to the player while wearing the trinket. 0 is equivalent to effect level 1.
		#Range: 0 ~ 255
		absorptionLevel = 0
		#The duration of the absorption effect, in ticks. When this hits zero, the effect is re-applied.
		#Range: > 1
		absorptionDuration = 400
		#The extra max health gained per level of Protection on the Golden Heart. This obeys the operation, so if you set maxHealthBoostOperation to either 1 or 2, it's recommended to keep this at 0.1 at most.
		#Range: 0.0 ~ 1.7976931348623157E308
		enchantmentMaxHealthIncrease = 1.0
		#The amount in which the duration of the absorption effect is reduced, in ticks. This allows for faster reapplication of the effect.
		#Range: > 0
		enchantmentAbsorptionReduction = 20

	[CurioSettings.GlassShieldSettings]
		#The duration, in ticks, for the Glass Shield to recharge after it blocks a hit. Extremely low values effectively make you invincible. It is recommended to make this greater than enchantmentCooldownReduction, unless mending is unobtainable in your modpack.
		#Range: > 0
		cooldownDuration = 400
		#The amount of ticks to remove from the Glass Shield cooldown if Mending is applied. Note that if another mod changes Mending to have multiple levels, this will be multiplied by the level of the enchant.
		#Range: > 0
		enchantmentCooldownReduction = 100
		#The percent chance per level of Unbreaking to prevent the Glass Shield from shattering after blocking a hit. This is rounded up to the nearest whole number in-game. If your modpack has the ability to grant you outrageous levels of unbreaking (looking at you, Apotheosis), this should be set to a low value or kept at the default.
		#Range: 0.0 ~ 100.0
		enchantmentFreeBlockChance = 2.0

	[CurioSettings.WardCrystalSettings]
		#The multiplier for incoming magic damage when wearing a Ward Crystal. 0.0 completely nullifies the attack, and 1.0 does not change the attack strength at all.
		#Range: 0.0 ~ 1.7976931348623157E308
		antiMagicMultiplierIncoming = 0.25
		#The multiplier for outgoing magic damage when wearing a Ward Crystal. 0.0 completely nullifies the attack, and 1.0 does not change the attack strength at all.
		#Range: 0.0 ~ 1.7976931348623157E308
		antiMagicMultiplierOutgoing = 0.25

	[CurioSettings.ShadowTreadsSettings]
		#The level of the speed effect applied to the player while in darkness. 0 is equivalent to effect level 1.
		#Range: 0 ~ 255
		darkspeedPotency = 0
		#The amount of passive speed granted by each level of Soul Speed.
		#Range: 0.0 ~ 1.7976931348623157E308
		enchantmentSpeedMultiplier = 0.05
		#The maximum light level in which the Shadow Charm takes effect. Values below 4 are not recommended, as sky light causes the minimum light value to always be 4 on the surface, even at midnight.
		#Range: 0 ~ 15
		maxLightLevel = 7

	[CurioSettings.DualityRingsSettings]
		#The damage multiplier of arrow projectiles while the Duality Rings are equipped. Values above 1.0 increase the damage, while values below 1.0 decrease the damage.
		#Range: 0.0 ~ 1.7976931348623157E308
		aroOfClubsMultiplier = 1.25
		#The level of the strength effect applied to the player when consuming Magic Garlic Bread while the Duality Rings are equipped.
		#Range: 0 ~ 255
		strengthLevel = 0
		#The duration of the strength effect, in ticks.
		#Range: > 1
		strengthDuration = 2400
		#The level of the health boost effect applied to the player when consuming Magic Garlic Bread while the Duality Rings are equipped.
		#Range: 0 ~ 255
		healthBoostLevel = 2
		#The duration of the health boost effect, in ticks.
		#Range: > 1
		healthBoostDuration = 2400

	[CurioSettings.FriendlyFireFlowerSettings]
		#The duration of Fire Resistance granted after taking fire damage, in ticks. This is multiplied by the level of Fire Protection on the item, +1.
		#Range: > 1
		fireResistanceDuration = 200
		#If set to false, prevents the Friendly Fire Flower from being damaged when granting Fire Resistance to the wearer. Note that this will not remove durability values from flowers, and existing damaged flowers will still show as damaged.
		canBeDamaged = true

	[CurioSettings.LunarCrystalSettings]
		#A 1 in X chance for an attacked entity to levitate upon being attacked while a Lunar Crystal is equipped.
		#Range: > 2
		levitationChance = 10
		#The duration of the Levitation effect, in ticks.
		#Range: > 1
		levitationDuration = 60
		#The level of the levitation effect. 0 is equivalent to effect level 1.
		#Range: 0 ~ 255
		levitationPotency = 2
		#The percentage in which the player's gravity is changed while the Lunar Crystal is equipped. Negative values reduce gravity, positive values increase it. -1 is not recommended, unless your planet needs you.
		#Range: -1.0 ~ 1.7976931348623157E308
		gravityModifier = -0.25
		#Set this to true to make my UUID exclusive easter egg apply to all players of the current modpack. Recommended for people named Luna playing singleplayer on a private modpack. Not so recommended in most other cases.
		everyoneIsLuna = false
		#The percentage of fall damage reduced per level of feather falling on this item. Set to 0 to effectively disable this feature.
		#Range: 0.0 ~ 1.0
		fallDamageReduction = 0.05

	[CurioSettings.HarpyFeatherSettings]
		#The cooldown between Harpy Feather jumps, in ticks.
		#Range: > 0
		jumpCooldown = 60
		#The force of the Harpy Feather jump. This goes by internal values, so tweaking may be required.
		#Range: 0.0 ~ 1.7976931348623157E308
		jumpForce = 0.42

[SuperCurioSettings]

	[SuperCurioSettings.SuperGoldenHeartSettings]
		#The duration of the Fractured effect, in ticks.
		#Range: > 1
		fracturedDuration = 6000
		#The level of the Fractured effect. Each level is 10% of max health lost. 0 is equal to level 1.
		#Range: 0 ~ 8
		fracturedPotency = 2
		#The cooldown of the diamond heart before you are allowed to revive again. This is in ticks. Extremely low values effectively make you unable to die.
		#Range: > 0
		revivalCooldown = 6000

	[SuperCurioSettings.SuperGlassShieldSettings]
		#Once this amount of ticks is exceeded, the next fatal blow will kill the wearer. At the default value, this will allow for four revives, unless somehow the wearer miraculously gets killed three times in a single tick.
		#Range: > 0
		revivalLimit = 3600
		#The amount of ticks added each time the Shield of Undying sustains a fatal blow. This stacks until it reaches the value defined in revivalLimit, in which the next fatal blow will kill the wearer.
		#Range: > 0
		shatterRevivalCooldown = 1200
		#The operation 2 modifier given to the player wearing this shield. This should be negative or zero.
		#Range: -1.0 ~ 0.0
		healthTradeoff = -0.8

	[SuperCurioSettings.SuperWardCrystalSettings]
		#The duration of all applied potion effects will be multiplied by this value.
		#Range: 0.0 ~ 2.0
		potionDurationMultiplier = 0.2

	[SuperCurioSettings.SuperShadowTreadsSettings]
		#The damage boost applied at noon (time 6000). This is always operation 2.
		#Range: 0.0 ~ 1.7976931348623157E308
		damageModifierMax = 0.2
		#The speed boost applied at midnight (time 18000). This is always operation 2.
		#Range: 0.0 ~ 1.7976931348623157E308
		speedModifierMax = 0.2

	[SuperCurioSettings.AscendedStarSettings]
		#The amount of additional slots granted upon equipping the star.
		#Range: 0 ~ 3
		bonusSlots = 1
		#The multiplier to all incoming damage the player receives.
		#Range: 1.0 ~ 1.7976931348623157E308
		damageMultiplier = 3.0
		#The amount of additional fortune levels granted upon equipping the star.
		#Range: > 0
		bonusFortune = 1
		#The amount of additional looting levels granted upon equipping the star.
		#Range: > 0
		bonusLooting = 1

